<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pic</string>
	</array>
	<key>foldingStartMarker</key>
	<string>#begin\b</string>
	<key>foldingStopMarker</key>
	<string>#end\b</string>
	<key>name</key>
	<string>Sequence Macros For Pic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(actor|object|pobject|placeholder_object)(\()(?:(\w+),)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.object.definition.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.definition.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arguments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(lconstraint_below|lconstraint|lifeline_constraint)(\()(\w+),</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.object.constraints.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.constraints.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.activation.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(active|inactive|complete|delete|pause|resume)(\()(\w+)(\));</string>
			<key>name</key>
			<string>meta.object.activation.sequence.pic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(comment)(\()(\w+),(\w+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.comment.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.comment.name.sequence.pic</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.line_movement.sequence.pic</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.box_size.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.comment.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>,(?= *[^ "][^"]+[,\)])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.sequence.pic.mary</string>
						</dict>
					</dict>
					<key>end</key>
					<string>,</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.sequence.pic.bob</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.comment.position.sequence.pic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=,)(?= *[^ "][^"]+["\)])</string>
					<key>end</key>
					<string>(?=["\)])</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parameters.sequence.pic</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.comment.size.sequence.pic</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(action|message|return_message|message_self|create_message|destroy_message)(\()(\w+),(?:(\w+),)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.message.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.message.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.sequence.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(#).*$</string>
			<key>name</key>
			<string>comment.line.sequence.pic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.(?:PS|PE)\b)</string>
			<key>name</key>
			<string>meta.preprocessor.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.control.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.sequence.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(step|async|sync|divider_line|section_line|elapsed_time)(\(\));</string>
			<key>name</key>
			<string>meta.control.sequence.pic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(link)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.object.definition.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.control.labeled.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arguments</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(begin_frame|end_frame)(\()(\w+),(\w+),?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.frame.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.frame.name.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.frame.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(begin_group|end_group)(\()(\w+),?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.group.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.group.name.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.group.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(object_constraint|begin_frame|end_frame|connect_to_comment|title)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.group.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.other.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(for|do|if|then|else)\b</string>
			<key>name</key>
			<string>meta.language.keywords.control.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.verbs.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(copy|move|line|arc|arrow|circle|ellipse|box)\b</string>
			<key>name</key>
			<string>meta.language.keywords.verbs.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.position.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(up|down|left|right|from|to|at|with|rad|radius|fill)\b</string>
			<key>name</key>
			<string>meta.language.keywords.position.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.attributes.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(invisible|invis|dashed|dotted|ljust|rjust)\b</string>
			<key>name</key>
			<string>meta.language.keywords.attributes.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.dimensions.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(boxwid|boxht|linewid|lineht|circlerad|arcrad|ellipsewid|ellipseht|movewid|moveht|textwid|textht|arrowwid|arrowht|dashwid|arrowhead|maxpsht|maxpswid|fillval|scale)\b</string>
			<key>name</key>
			<string>meta.language.keywords.dimensions.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.coordinates.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(start|end|ht|wid|s|e|w|n|se|ne|sw|nw|x|y)\b</string>
			<key>name</key>
			<string>meta.language.keywords.coordinates.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.definition.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.definition.object.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(define|object)\b (\w+)</string>
			<key>name</key>
			<string>meta.language.definition.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.special.constants.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(Here|last|same)\b</string>
			<key>name</key>
			<string>meta.language.special.constants.pic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arguments</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arguments</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.argument.positional.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;!\\)(\$\d+)</string>
			<key>name</key>
			<string>meta.language.argument.positional.pic</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\f(B|I|P)</string>
					<key>name</key>
					<string>meta.preprocessor.font.command.pic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arguments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pic</string>
	<key>uuid</key>
	<string>F8B0F1A7-37C8-49A2-BC2C-3D330F88BA51</string>
</dict>
</plist>
