<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pic</string>
	</array>
	<key>foldingStartMarker</key>
	<string>#begin\b</string>
	<key>foldingStopMarker</key>
	<string>#end\b</string>
	<key>name</key>
	<string>Sequence Macros For Pic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(actor|object|pobject|placeholder_object)(\()(?:(\w+),)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.object.definition.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.definition.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(lconstraint_below|lconstraint|lifeline_constraint)(\()(\w+),</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.object.constraints.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.constraints.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.activation.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(active|inactive|complete)(\()(\w+)(\));</string>
			<key>name</key>
			<string>meta.object.activation.sequence.pic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(comment)(\()(\w+),(\w+),([^,]*),([^"]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.comment.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.comment.name.sequence.pic</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.line_movement.sequence.pic</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.box_size.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.comment.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(message|return_message|create_message|destroy_message)(\()(\w+),(\w+),?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.message.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.object.sequence.pic</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\));</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.sequence.pic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.message.sequence.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.sequence.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^|\s)(#).*$</string>
			<key>name</key>
			<string>comment.line.sequence.pic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.(?:PS|PE)\b)</string>
			<key>name</key>
			<string>meta.preprocessor.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.sequence.pic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.sequence.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(step|async|sync)(\(\));</string>
			<key>name</key>
			<string>meta.control.sequence.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sequence.macro</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(delete|object_constraint|begin_frame|end_frame|connect_to_comment)(.*?)(\));</string>
			<key>name</key>
			<string>meta.object.other.sequence.pic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.keywords.pic</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(copy|up|ht|wid|move)\b</string>
			<key>name</key>
			<string>meta.language.keywords.pic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.pic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\f(B|I|P)</string>
					<key>name</key>
					<string>meta.preprocessor.font.command.pic</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.pic</string>
	<key>uuid</key>
	<string>F8B0F1A7-37C8-49A2-BC2C-3D330F88BA51</string>
</dict>
</plist>
